version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:c54e17785d4cd79cbbd9032dae84c2dce3937697d9c79086b57994a53b712f9f
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 30
      - run: npm run test
      - run: mkdir docs
      - run: mv index.html docs/index.html
      - run: mv index.bundle.js docs/index.bundle.js
      - store_artifacts:
          path: docs
