version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:545b744e11cbcaaa5c32c2338bd4aa99a98d159fab41f1b2c98c763ffb384af1
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 30
      - run: npm run test
      - run: mkdir docs
      - run: mv index.html docs/index.html
      - run: mv index.bundle.js docs/index.bundle.js
      - store_artifacts:
          path: docs
