version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:332152836a053c9af95682c08949fa23ac6ebe5f7e0d60db9c1f5ae75e499ab6
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 30
      - run: npm run test
      - run: mkdir docs
      - run: mv index.html docs/index.html
      - run: mv index.bundle.js docs/index.bundle.js
      - store_artifacts:
          path: docs
