version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:0c0e93d8a91f5e59d9a3dad3ed049a465fd6218186fc1ca29e56cd7ec2b89d1b
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 30
      - run: npm run test
      - run: mkdir docs
      - run: mv index.html docs/index.html
      - run: mv index.bundle.js docs/index.bundle.js
      - store_artifacts:
          path: docs
