version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:0a674f18f46711824f5a9667db7e7c6f6754d1848ccd8e7c64b13d8772cda0f1
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 30
      - run: npm run test
      - run: mkdir docs
      - run: mv index.html docs/index.html
      - run: mv index.bundle.js docs/index.bundle.js
      - store_artifacts:
          path: docs
