version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:1a956044c98c1feee92632ce85ca7dfb01d58c87a3c3cdd9e5b0531bb6eef47d
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm run build
      - store_artifacts:
          path: dist
