version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:1c166b016a97ed11bf26f9040827e754cad1019e641ae40811d935db2b48d303
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 30
      - run: npm run test
      - run: mkdir docs
      - run: mv index.html docs/index.html
      - run: mv index.bundle.js docs/index.bundle.js
      - store_artifacts:
          path: docs
